apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sa-frontend
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
        - name: sa-frontend
          image: k8app/frontendapp
          imagePullPolicy: Never
          ports:
            - containerPort: 80