version: '2'
services:
  frontendapp: 
    image: ${REGURL}k8app/frontendapp
    ports:
      - 8180:80
      #- 443:443
  backendapp: 
    image: ${REGURL}k8app/backendapp
    ports:
      - 3443:3443